### ISSUE TITLE
There is any package require to install before activating the theme?

### ISSUE THREAD

**Issue by aminasoode** [peymanslh/MyBlog#1]
Hi.
I download this theme as a zip file *MyBlog-master.zip* and extracted it on my *wp-content/themes* wordpress folder.
After activating the theme in wordpress panel, only text and post assets (like image and videos) would appears and the blog element won't load up.

I'm using a shared host for my blog and I do not access to server terminal for installing additional packages. There is any require packages that need to be install on server side before activating the theme?
![screenshot_4](https://cloud.githubusercontent.com/assets/739228/10392553/e657195a-6e94-11e5-8255-2be989de8b42.png)

**Comment by peymanslh** [comment]
No, you don't need to install any packages.
Please check your theme directory permission and change it to 775.

**Comment by aminasoode** [comment]
I changed the theme directory permission to 775 in my DIrectAdmin panel.
Unfortunately it doesn't solve the problem.

![screenshot_4](https://cloud.githubusercontent.com/assets/739228/10400764/9654d5b8-6ec7-11e5-9f1b-5a8ce99fb3bc.png)

**Comment by peymanslh** [comment]
Please download it again from GitHub.

**Comment by aminasoode** [comment]
I download and reactive the theme, but it wouldn't fix the problem. I also install the theme on my local machine with php version 5.6; same problem happened.

**Comment by aminasoode** [comment]
My friend who I get the host from loged in to my wordpress and activate the theme, and everything load correctly!
He didn't do anything. It's weird :|
